ALTER TABLE `SHOP` 
ADD COLUMN `MOBILES` VARCHAR(200) NULL DEFAULT NULL AFTER `PIC_ID`;

CREATE TABLE `REF_PRODUCT` (
  `ID` bigint(20) NOT NULL,
  `REF_PRODUCT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_REF_PROD_ID_PROD_ID` FOREIGN KEY (`ID`) REFERENCES `PRODUCT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;