ALTER TABLE `woyao`.`CHAT_MSG` 
ADD COLUMN `PAYED` BIT(1) NULL DEFAULT 0 AFTER `PROFILE_WX_TO`,
ADD COLUMN `REMOTE_ADDR` VARCHAR(30) NULL DEFAULT NULL AFTER `PAYED`,
ADD INDEX `IDX_PAYED` USING BTREE (`PAYED` ASC),
ADD INDEX `IDX_FREE` USING BTREE (`FREE` ASC);
