CREATE SCHEMA `cat2` DEFAULT CHARACTER SET utf8mb4 ;

CREATE USER 'cat2'@'localhost' IDENTIFIED BY 'C@t2_2016';
CREATE USER 'cat2'@'%' IDENTIFIED BY 'C@t2_2016_Snowm';

GRANT ALL PRIVILEGES ON `cat2`.* TO 'cat2'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `cat2`.* TO 'cat2'@'%';