CREATE TABLE `ID_GENERATOR` (
  `GEN_NAME` varchar(255) DEFAULT NULL,
  `GEN_VALUE` int(11) DEFAULT NULL,
  KEY `IDX_GEN_NAME` (`GEN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PERMISSION` (
  `ID` bigint(20) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ROLE` (
  `ID` bigint(20) NOT NULL,
  `CODE` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ROLE_PERMISSION` (
  `ID` bigint(20) NOT NULL,
  `PERMISSION_ID` bigint(20) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_m2r1sqbtxt5fo39ax55fiq4l0` (`PERMISSION_ID`),
  KEY `FK_fn5mhmaqw72j8387h40mmj8sn` (`ROLE_ID`),
  CONSTRAINT `FK_fn5mhmaqw72j8387h40mmj8sn` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`),
  CONSTRAINT `FK_m2r1sqbtxt5fo39ax55fiq4l0` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PROFILE` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `CREDENTIALS_EXPIRED` bit(1) DEFAULT NULL,
  `EMAIL` varchar(200) DEFAULT NULL,
  `EXPIRED` bit(1) DEFAULT NULL,
  `GENDER` int(11) DEFAULT NULL,
  `LOCKED` bit(1) DEFAULT NULL,
  `MOBILE_NUMBER` varchar(20) DEFAULT NULL,
  `NICKNAME` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `TYPE` int(11) NOT NULL,
  `USERNAME` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME_UNIQUE` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PROFILE_ROLE` (
  `ID` bigint(20) NOT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `PROFILE_ID` bigint(20) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PROFILE_ID` (`PROFILE_ID`),
  KEY `FK_ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `FK_fv5l1pbb2u5mkuicpj9udk0lk` FOREIGN KEY (`PROFILE_ID`) REFERENCES `PROFILE` (`ID`),
  CONSTRAINT `FK_ofvbhn5g14udp3bausuqauv8s` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `GLOBAL_ACCESS_TOKEN` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `TOKEN` varchar(1000) NOT NULL,
  `EFFECTIVE` bit(1) DEFAULT NULL,
  `EXPIRES_IN` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `JSAPI_TICKET` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `EFFECTIVE` bit(1) DEFAULT NULL,
  `EXPIRES_IN` bigint(20) NOT NULL,
  `TICKET` varchar(1000) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `USER_ACCESS_TOKEN` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `TOKEN` varchar(1000) NOT NULL,
  `EFFECTIVE` bit(1) DEFAULT NULL,
  `EXPIRES_IN` bigint(20) NOT NULL,
  `OPEN_ID` varchar(50) NOT NULL,
  `PROFILE_WX_ID` bigint(20) DEFAULT NULL,
  `REFRESH_TOKEN` varchar(255) NOT NULL,
  `SCOPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_AT_OPEN_ID` (`OPEN_ID`),
  UNIQUE KEY `UK_USER_AT_PROF_WX_ID` (`PROFILE_WX_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PICTURE` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `PATH` varchar(255) NOT NULL,
  `URL` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SHOP` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `ADDRESS` varchar(255) NOT NULL,
  `DESCRIPTION` text,
  `LATITUDE` double DEFAULT NULL,
  `LONGITUDE` double DEFAULT NULL,
  `MANAGER_PROFILE_ID` bigint(20) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `PUBLIC_ACC_URL` varchar(255) DEFAULT NULL,
  `PIC_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_PIC_ID` (`PIC_ID`),
  CONSTRAINT `FK_SHOP_PIC_ID` FOREIGN KEY (`PIC_ID`) REFERENCES `PICTURE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SHOP_PICTURE` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `SHOP_ID` bigint(20) NOT NULL,
  `PIC_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_PIC_ID` (`PIC_ID`),
  KEY `IDX_SHOP_ID` (`SHOP_ID`),
  CONSTRAINT `FK_SHOP_PIC_PIC_ID` FOREIGN KEY (`PIC_ID`) REFERENCES `PICTURE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `CHAT_ROOM` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `SHOP_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SHOP_ID` (`SHOP_ID`),
  CONSTRAINT `FK_plnoy6jf4vebrokpnxdk4q0fj` FOREIGN KEY (`SHOP_ID`) REFERENCES `SHOP` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PRODUCT` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `DESCRIPTION` text,
  `NAME` varchar(255) NOT NULL,
  `PRODUCT_TYPE` int(11) NOT NULL,
  `UNIT_PRICE` int(11) NOT NULL,
  `PIC_ID` bigint(20) DEFAULT NULL,
  `SHOP_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROD_PIC_ID` (`PIC_ID`),
  KEY `IDX_PROD_SHOP_ID` (`SHOP_ID`),
  CONSTRAINT `FK_PROD_PIC_ID` FOREIGN KEY (`PIC_ID`) REFERENCES `PICTURE` (`ID`),
  CONSTRAINT `FK_PROD_SHOP_ID` FOREIGN KEY (`SHOP_ID`) REFERENCES `SHOP` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PRODUCT_PICTURE` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `PRODUCT_ID` bigint(20) NOT NULL,
  `PIC_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_rpt792x17s4osfvgyn9ypimyh` (`PIC_ID`),
  CONSTRAINT `FK_rpt792x17s4osfvgyn9ypimyh` FOREIGN KEY (`PIC_ID`) REFERENCES `PICTURE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MSG_PRODUCT` (
  `CODE` varchar(20) DEFAULT NULL,
  `HOLD_TIME` int(11) NOT NULL,
  `ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_MSG_PROD_ID_PROD_ID` FOREIGN KEY (`ID`) REFERENCES `PRODUCT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PROFILE_WX` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `COUNTRY` varchar(50) DEFAULT NULL,
  `GENDER` int(11) NOT NULL,
  `HEAD_IMG` varchar(255) DEFAULT NULL,
  `NICKNAME` varchar(100) DEFAULT NULL,
  `OPENID` varchar(50) NOT NULL,
  `PRIVILEGE` varchar(255) DEFAULT NULL,
  `PROVINCE` varchar(50) DEFAULT NULL,
  `UNIONID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_OPEN_ID` (`OPENID`),
  KEY `IDX_LAST_MD_DT` (`LAST_MODIFIED_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `CHAT_MSG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `ROOM_ID` bigint(20) DEFAULT NULL,
  `CLIENT_MSG_ID` bigint(20) DEFAULT NULL,
  `CONTENT` varchar(255) DEFAULT NULL,
  `FREE` bit(1) DEFAULT NULL,
  `PROFILE_WX_FROM` bigint(20) NOT NULL,
  `ORDER_ID` bigint(20) DEFAULT NULL,
  `PIC_URL` varchar(100) DEFAULT NULL,
  `PRODUCT_ID` bigint(20) DEFAULT NULL,
  `TEXT` varchar(500) NOT NULL,
  `PROFILE_WX_TO` bigint(20) DEFAULT NULL,
  `PAYED` bit(1) DEFAULT b'0',
  `REMOTE_ADDR` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_ORD_ID` (`ORDER_ID`),
  KEY `IDX_ROOM_ID` (`ROOM_ID`) USING BTREE,
  KEY `IDX_CR_DT` (`CREATION_DATE`),
  KEY `IDX_FROM` (`PROFILE_WX_FROM`),
  KEY `IDX_TO` (`PROFILE_WX_TO`),
  KEY `IDX_PAYED` (`PAYED`) USING BTREE,
  KEY `IDX_FREE` (`FREE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2835 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ORDER_PREPAY_INFO` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `APP_ID` varchar(32) DEFAULT NULL,
  `CODE_URL` varchar(100) DEFAULT NULL,
  `DEVICE_INFO` varchar(32) DEFAULT NULL,
  `ERR_CODE` varchar(32) DEFAULT NULL,
  `ERR_CODE_DESC` varchar(200) DEFAULT NULL,
  `MCH_ID` varchar(32) DEFAULT NULL,
  `NONCE_STR` varchar(32) DEFAULT NULL,
  `PRE_PAY_ID` varchar(80) DEFAULT NULL,
  `RESULT_CODE` varchar(16) DEFAULT NULL,
  `RETURN_CODE` varchar(20) DEFAULT NULL,
  `RETURN_MSG` varchar(200) DEFAULT NULL,
  `SIGN` varchar(32) DEFAULT NULL,
  `TRADE_TYPE` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_CR_DT` (`CREATION_DATE`),
  KEY `IDX_PREPAY_ID` (`PRE_PAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ORDER_RESULT_INFO` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `ERR_CODE` varchar(32) DEFAULT NULL,
  `ERR_CODE_DESC` varchar(200) DEFAULT NULL,
  `OPEN_ID` varchar(50) NOT NULL,
  `RESULT_CODE` varchar(20) DEFAULT NULL,
  `RETURN_CODE` varchar(10) NOT NULL,
  `TIME_END` datetime DEFAULT NULL,
  `TRANSACTION_ID` varchar(32) DEFAULT NULL,
  `VERSION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PURCHASE_ORDER` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `MSG_ID` bigint(20) DEFAULT NULL,
  `ORDER_NO` varchar(32) NOT NULL,
  `SPBILL_CREATE_IP` varchar(255) NOT NULL,
  `ORDER_STATUS` int(11) DEFAULT NULL,
  `TOTAL_FEE` int(11) NOT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `CONSUMER_ID` bigint(20) NOT NULL,
  `PREPAY_INFO_ID` bigint(20) DEFAULT NULL,
  `RESULT_INFO_ID` bigint(20) DEFAULT NULL,
  `TO_PROFILE_WX_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_ORDER_NO` (`ORDER_NO`),
  KEY `IDX_CONSUMER_ID` (`CONSUMER_ID`),
  KEY `IDX_PREPAY_INF_ID` (`PREPAY_INFO_ID`),
  KEY `IDX_RESULT_INF_ID` (`RESULT_INFO_ID`),
  KEY `IDX_CREATION_DT` (`CREATION_DATE`),
  KEY `IDX_ORDER_STATUS` (`ORDER_STATUS`) USING BTREE,
  KEY `IDX_TO_PROF_WX_ID_idx` (`TO_PROFILE_WX_ID`),
  CONSTRAINT `FK_ORD_CONSUMER_ID` FOREIGN KEY (`CONSUMER_ID`) REFERENCES `PROFILE_WX` (`ID`),
  CONSTRAINT `FK_ORD_PREPAY_INF_ID` FOREIGN KEY (`PREPAY_INFO_ID`) REFERENCES `ORDER_PREPAY_INFO` (`ID`),
  CONSTRAINT `FK_ORD_RESULT_INF_ID` FOREIGN KEY (`RESULT_INFO_ID`) REFERENCES `ORDER_RESULT_INFO` (`ID`),
  CONSTRAINT `FK_ORD_TO_PROF_WX_ID` FOREIGN KEY (`TO_PROFILE_WX_ID`) REFERENCES `PROFILE_WX` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ORDER_ITEM` (
  `ID` bigint(20) NOT NULL,
  `DELETED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `QUANTITY` int(11) NOT NULL,
  `TOTAL_FEE` bigint(20) NOT NULL,
  `UNIT_PRICE` int(11) NOT NULL,
  `ORDER_ID` bigint(20) NOT NULL,
  `PRODUCT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ORD_ID` (`ORDER_ID`),
  KEY `FK_PROD_ID` (`PRODUCT_ID`),
  CONSTRAINT `FK_2lm43bk1tc4fx944flwnenjqx` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`),
  CONSTRAINT `FK_67aq174ged86cpv5ejbpkpqpy` FOREIGN KEY (`ORDER_ID`) REFERENCES `PURCHASE_ORDER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

