CREATE TABLE `permission` (
  `ID` bigint(20) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `role` (
  `ID` bigint(20) NOT NULL,
  `CODE` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `VISIBLE` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `role_permission` (
  `ID` bigint(20) NOT NULL,
  `PERMISSION_ID` bigint(20) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK9C6EC93886876E26` (`PERMISSION_ID`),
  KEY `FK9C6EC938563E21C6` (`ROLE_ID`),
  CONSTRAINT `fk_role_permission_role_id` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`),
  CONSTRAINT `fk_role_permission_permission_id` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `permission` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `profile` (
  `ID` bigint(20) NOT NULL,
  `CREDENTIALS_EXPIRED` tinyint(1) DEFAULT NULL,
  `EMAIL` varchar(200) DEFAULT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT 1,
  `EXPIRED` tinyint(1) NOT NULL DEFAULT 0,
  `GENDER` int(11) NOT NULL,
  `LOCKED` tinyint(1) NOT NULL DEFAULT 0,
  `MOBILE_NUMBER` varchar(20) DEFAULT NULL,
  `MOBILE_NUMBER_RECMSG` varchar(20) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `NICKNAME` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `TYPE` int(11) NOT NULL,
  `USERNAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `profile_role` (
  `ID` bigint(20) NOT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `PROFILE_ID` bigint(20) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKD4D4296C15DB75CE` (`PROFILE_ID`),
  KEY `FKD4D4296C563E21C6` (`ROLE_ID`),
  CONSTRAINT `fk_profile_role_role_id` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`),
  CONSTRAINT `fk_profile_role_profile_id` FOREIGN KEY (`PROFILE_ID`) REFERENCES `profile` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
