DROP TABLE IF EXISTS GLOBAL_ACCESS_TOKEN;
DROP TABLE IF EXISTS JSAPI_TICKET;
DROP TABLE IF EXISTS USER_ACCESS_TOKEN;

DROP TABLE IF EXISTS ORDER_ITEM;
DROP TABLE IF EXISTS PURCHASE_ORDER;
DROP TABLE IF EXISTS ORDER_PREPAY_INFO;
DROP TABLE IF EXISTS ORDER_RESULT_INFO;

DROP TABLE IF EXISTS MSG_PRODUCT;
DROP TABLE IF EXISTS PRODUCT_PICTURE;
DROP TABLE IF EXISTS PAID_MSG_PRODUCT_CONFIG;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CHAT_ROOM;
DROP TABLE IF EXISTS SHOP_PICTURE;
DROP TABLE IF EXISTS SHOP;

DROP TABLE IF EXISTS CHAT_MSG;

DROP TABLE IF EXISTS PROFILE_WX;
DROP TABLE IF EXISTS PICTURE;


DROP TABLE IF EXISTS ROLE_PERMISSION;
DROP TABLE IF EXISTS PROFILE_ROLE;
DROP TABLE IF EXISTS PROFILE;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS PERMISSION;

DROP TABLE IF EXISTS ID_GENERATOR;